name: s3-browser
version: git
summary: S3 Browser
description: S3 Browser
base: core18
parts:
  s3-browser:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six
      - libgtk-3-dev
apps:
  s3-browser:
    command: bin/setup