name: s3-browser
version: git
summary: S3 Browser
description: |
  OfflineIMAP is software that downloads your email mailbox(es) as local
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.
base: core18
parts:
  s3-browser:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six
      - libgtk-3-dev

apps:
  s3-browser:
    command: python3 ./setup