name: clan
version: git
summary: S3 Browser
description: S3 Browser
base: core18
parts:
  clan:
    plugin: python
    source: .
    stage-packages:
      - libgtk-3-dev
      - python3-gi
apps:
  clan:
    command: clan