name: clan
version: git
summary: S3 Browser
description: S3 Browser
parts:
  clan:
    plugin: python
    source: .
    stage-packages:
      - libgtk-3-dev
      - python3-gi
      - gobject-introspection
      - gir1.2-gtk-3.0
      - python3-click
      - python3-gi-cairo
      - python3-cairo
apps:
  clan:
    command: clan