name: clan
version: git
summary: S3 Browser
description: S3 Browser
base: core18
parts:
  clan:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six
      - libgtk-3-dev
apps:
  clan:
    command: clan