name:           s3-browser
version:        '1.0'
summary:        Example python snap app
description:    Example python snap app
confinement:    devmode
grade:          stable
base: core18
apps:
  s3-browser:
    command:    s3-browser

parts:
  s3-browser:
    plugin:     python
